### ISSUE TITLE
Clean up the bloat from repository

### ISSUE THREAD

**Issue by frol** [near/borsh#67] opened 2020-03-24 01:21 UTC
It is painful to clone the repository (it took me 10 minutes lately).

`/docs/criterion` folder is 200MB. Can we trim it down?

**Comment by nearmax** [comment] 2020-06-11 21:47
`/docs/criterion` allows us to track performance changes. It is large because it contains exhaustive data that can be used to reproduce the metrics. Currently when we run a performance optimization our workflow is the following:
* Attempt performance optimization on the code;
* Run criterion and make it compare the new metrics to the old metrics;
* Merge performance optimization if the metrics are overall better.

Without this folder we won't be able to rely on the built-in functionality of criterion to automatically tell us whether the performance improvement happened. Note, that this is better than manually comparing metrics, because criterion performance statistical analysis and reports important data, like what is the p-value, what is the chance the improvement actually happened and it is not just a fluke, etc.

Until there is no better solution to track performance improvements I am going to close this issue.

**Closed by nearmax** 2020-06-11 21:47 UTC
Labels: housekeeping
